Upgrade dependencies and fix errors
attila/metalsmith-rollup pull request #6
Opened 2019-01-21 03:55 UTC by reubano

2019-11-11 15:41 UTC, bedax commented
any news on this? I think it needs accepting or this repo should be marked as abandoned.

2019-11-12 16:18 UTC, attila requested changes
Thanks for your contribution. I do not use metalsmith much anymore but happy to see others care! I think the change is good but it needs more work. I understand that this project needs better tooling but let's not mix coding styles and let's not bring in unnecessary dependencies if possible. Will happily re-review again if needed!

2019-11-12 16:18 UTC, attila commented on lib/index.js
> +const debug = Debug('metalsmith-rollup')
Let's not add debug support just like this, or if we think it's needed, let's add debugging to all key areas.

2019-11-12 16:18 UTC, attila commented on lib/index.js
> +const { sep, resolve, basename } = require('path')
Unnecessary change.

2019-11-12 16:18 UTC, attila commented on lib/index.js
> +  return p.split(sep).filter((q) => {
Unnecessary coding style change

2019-11-12 16:18 UTC, attila commented on package.json
> +    "yarn": "^1.13.0"
Do we really need yarn here? 🤔

2019-11-22 14:36 UTC, bedax commented
These comments seem like something that can be fixed after the PR is accepted, given that this repo is currently broken, and the PR is working.

I think it is important to remember that this plugin is listed on the Metalsmith homepage, and so if you are content to leave it in a broken state, you should add a unmaintained notice.

2019-11-25 10:14 UTC, attila commented
Thank you for your contribution and continued care towards this project @bedax 
I will try and find some time to go through the changes and sort out the problems with the PR.

2023-02-26 20:44 UTC, attila commented
Feel free to fork this repository, I do not have plans to maintain it any longer.

Thank you for your continued care!

2023-02-26 20:44 UTC, closed without merging